namespace InlineComposition;

public static partial class Attributes {
    public const string InlineFinalizerAttribute = """
    // <auto-generated>
    #pragma warning disable
    #nullable enable annotations
    
    
    namespace InlineCompositionAttributes;

    /// <summary>
    /// The Method under this attribute will be inlined in the finalizer.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    internal sealed class InlineFinalizerAttribute : Attribute {
        /// <summary>
        /// Indicates whether this method gets inlined before the other finalizers or after.
        /// </summary>
        public bool First { get; init; }
    }
    
    """;
}
