namespace InlineComposition;

public static partial class Attributes {
    public const string InlineAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        using System;
    
        namespace InlineCompositionAttributes;

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T7">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6, T7> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T7">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T8">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6, T7, T8> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T7">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T8">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T9">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6, T7, T8, T9> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T7">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T8">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T9">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T10">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T7">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T8">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T9">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T10">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T11">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> : Attribute { }

        /// <summary>
        /// Generates a partial class/struct which includes all members listed in the typeParams.
        /// </summary>
        /// <typeparam name="T1">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T2">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T3">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T4">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T5">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T6">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T7">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T8">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T9">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T10">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T11">class/struct which members gets inlined.</typeparam>
        /// <typeparam name="T12">class/struct which members gets inlined.</typeparam>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{NAME}}", "{{VERSION}}")]
        internal sealed class InlineAttribute<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> : Attribute { }

        """;
}
