using AssemblyVersionInfo;

namespace InlineComposition;

public static partial class Attributes {
    public const string InlineFinalizerAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !INLINECOMPOSITION_EXCLUDE_ATTRIBUTES

        using System;

        namespace InlineCompositionAttributes;

        /// <summary>
        /// The Method under this attribute will be inlined in the finalizer.
        /// </summary>
        [AttributeUsage(AttributeTargets.Method)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Assembly.NAME}}", "{{Assembly.VERSION_MAJOR_MINOR_BUILD}}")]
        internal sealed class InlineFinalizerAttribute : Attribute {
            /// <summary>
            /// Indicates whether this method gets inlined before the other finalizers or after.
            /// </summary>
            public bool First { get; init; }
        }

        #endif

        """;
}
