using AssemblyVersionInfo;

namespace InlineComposition;

public static partial class Attributes {
    public const string NoInlineAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !INLINECOMPOSITION_EXCLUDE_ATTRIBUTES

        using System;

        namespace InlineCompositionAttributes;

        /// <summary>
        /// <para>Only usefule in a class/struct with a <see cref="InlineBaseAttribute"/>.</para>
        /// <para>Skips/Ignores this member.</para>
        /// </summary>
        [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Event | AttributeTargets.Method)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Assembly.NAME}}", "{{Assembly.VERSION_MAJOR_MINOR_BUILD}}")]
        internal sealed class NoInlineAttribute : Attribute { }

        #endif

        """;
}
